language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository
script: cd cliffhanger/ && ./gradlew test
branches:
  except:
  - gh-pages
notifications:
  email: false
sudo: false
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
